### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/webhook#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

**Comment by lasley** [comment]
Curious - is this repo even possible? I have not yet been able to successfully make an Odoo web hook due to https://github.com/odoo/odoo/issues/7766

**Comment by lasley** [comment]
No tasks, my question can be discussed in #3. Closing
