### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by devingfx** [OCA/webhook#7]
Why is there an empty repo with no code at all, no doc, no wiki, no explainations?

Please delete this "false hope" repo...

**Comment by pedrobaeza** [comment]
Or contribute it yourself with some modules :wink: See that there are several pull requests for filling it.

**Comment by devingfx** [comment]
If I was searching for webhooks modules it's because I'm unable to code it... sadly :(
(I'm front-end ;) )

I hadn't seen the PRs though...

You can maybe write a little README explaining the reason why this repo exists, and the remaining work to be done by contributions ;) 

Thx for the reply btw !
